/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type RootModelStr = string

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greeting: {
input: void | undefined
output: RootModelStr
}
get_perception_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_records: {
input: void | undefined
output: RootModelDictStrAny
}
start_perception: {
input: void | undefined
output: RootModelDictStrAny
}
stop_perception: {
input: void | undefined
output: RootModelDictStrAny
}
clear_records: {
input: void | undefined
output: RootModelDictStrAny
}
get_buffered_events: {
input: void | undefined
output: RootModelDictStrAny
}
get_processing_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_events: {
input: void | undefined
output: RootModelDictStrAny
}
get_activities: {
input: void | undefined
output: RootModelDictStrAny
}
get_event_by_id: {
input: void | undefined
output: RootModelDictStrAny
}
get_activity_by_id: {
input: void | undefined
output: RootModelDictStrAny
}
start_processing: {
input: void | undefined
output: RootModelDictStrAny
}
stop_processing: {
input: void | undefined
output: RootModelDictStrAny
}
finalize_current_activity: {
input: void | undefined
output: RootModelDictStrAny
}
cleanup_old_data: {
input: void | undefined
output: RootModelDictStrAny
}
get_persistence_stats: {
input: void | undefined
output: RootModelDictStrAny
}
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
