/* eslint-disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

export type Name = string
export type RootModelStr = string
export type Limit = number
export type Eventtype = (string | null)
export type Starttime = (string | null)
export type Endtime = (string | null)
export type Limit1 = number
export type Eventtype1 = (string | null)
export type Starttime1 = (string | null)
export type Endtime1 = (string | null)
export type Limit2 = number
export type Eventid = string
export type Activityid = string
export type Days = number
export type Version = number
export type Limit3 = number
export type Provider = string
export type Apikey = string
export type Model = string
export type Baseurl = string
export type Databasepath = (string | null)
export type Screenshotsavepath = (string | null)
export type Agent = string
export type Plandescription = string
export type Taskid = string
export type Taskid1 = string
export type Limit4 = number
export type Status = (string | null)
export type Hashes = string[]
export type Maxagehours = number

/**
 * Commands Input and Output Schemas
 */
export interface Commands {
greeting: {
input: Person
output: RootModelStr
}
get_perception_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_records: {
input: GetRecordsRequest
output: RootModelDictStrAny
}
start_perception: {
input: void | undefined
output: RootModelDictStrAny
}
stop_perception: {
input: void | undefined
output: RootModelDictStrAny
}
clear_records: {
input: void | undefined
output: RootModelDictStrAny
}
get_buffered_events: {
input: void | undefined
output: RootModelDictStrAny
}
get_processing_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_events: {
input: GetEventsRequest
output: RootModelDictStrAny
}
get_activities: {
input: GetActivitiesRequest
output: RootModelDictStrAny
}
get_event_by_id: {
input: GetEventByIdRequest
output: RootModelDictStrAny
}
get_activity_by_id: {
input: GetActivityByIdRequest
output: RootModelDictStrAny
}
start_processing: {
input: void | undefined
output: RootModelDictStrAny
}
stop_processing: {
input: void | undefined
output: RootModelDictStrAny
}
finalize_current_activity: {
input: void | undefined
output: RootModelDictStrAny
}
cleanup_old_data: {
input: CleanupOldDataRequest
output: RootModelDictStrAny
}
get_persistence_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_activities_incremental: {
input: GetActivitiesIncrementalRequest
output: RootModelDictStrAny
}
get_activity_count_by_date: {
input: GetActivityCountByDateRequest
output: RootModelDictStrAny
}
start_system: {
input: void | undefined
output: RootModelDictStrAny
}
stop_system: {
input: void | undefined
output: RootModelDictStrAny
}
get_system_stats: {
input: void | undefined
output: RootModelDictStrAny
}
get_database_path: {
input: void | undefined
output: RootModelDictStrAny
}
get_settings_info: {
input: void | undefined
output: RootModelDictStrAny
}
update_settings: {
input: UpdateSettingsRequest
output: RootModelDictStrAny
}
create_task: {
input: CreateTaskRequest
output: RootModelDictStrAny
}
execute_task: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
delete_task: {
input: DeleteTaskRequest
output: RootModelDictStrAny
}
get_tasks: {
input: GetTasksRequest
output: RootModelDictStrAny
}
get_available_agents: {
input: GetAvailableAgentsRequest
output: RootModelDictStrAny
}
get_task_status: {
input: ExecuteTaskRequest
output: RootModelDictStrAny
}
get_image_stats: {
input: void | undefined
output: RootModelDict
}
get_cached_images: {
input: GetImagesRequest
output: RootModelDict
}
cleanup_old_images: {
input: CleanupImagesRequest
output: RootModelDict
}
clear_memory_cache: {
input: void | undefined
output: RootModelDict
}
}
/**
 * A simple model representing a person.
 * 
 * @property name - The name of the person.
 */
export interface Person {
name: Name
}
export interface RootModelDictStrAny {
[k: string]: unknown
}
/**
 * Request parameters for getting records.
 * 
 * @property limit - Maximum number of records to return (1-1000).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetRecordsRequest {
limit?: Limit
eventType?: Eventtype
startTime?: Starttime
endTime?: Endtime
}
/**
 * Request parameters for getting events.
 * 
 * @property limit - Maximum number of events to return (1-500).
 * @property eventType - Optional event type filter.
 * @property startTime - Optional start time filter (ISO format).
 * @property endTime - Optional end time filter (ISO format).
 */
export interface GetEventsRequest {
limit?: Limit1
eventType?: Eventtype1
startTime?: Starttime1
endTime?: Endtime1
}
/**
 * Request parameters for getting activities.
 * 
 * @property limit - Maximum number of activities to return (1-100).
 */
export interface GetActivitiesRequest {
limit?: Limit2
}
/**
 * Request parameters for getting event by ID.
 * 
 * @property eventId - The event ID.
 */
export interface GetEventByIdRequest {
eventId: Eventid
}
/**
 * Request parameters for getting activity by ID.
 * 
 * @property activityId - The activity ID.
 */
export interface GetActivityByIdRequest {
activityId: Activityid
}
/**
 * Request parameters for cleaning up old data.
 * 
 * @property days - Number of days to keep (1-365).
 */
export interface CleanupOldDataRequest {
days?: Days
}
/**
 * Request parameters for incremental activity updates.
 * 
 * @property version - The current version number from client (starts at 0).
 * @property limit - Maximum number of new activities to return (1-100).
 */
export interface GetActivitiesIncrementalRequest {
version?: Version
limit?: Limit3
}
/**
 * Request parameters for getting activity count by date.
 * 
 * Returns the total activity count for each date (不分页，获取所有日期的总数).
 */
export interface GetActivityCountByDateRequest {

}
/**
 * Request parameters for updating application settings.
 * 
 * @property llm - LLM configuration to update (optional).
 * @property databasePath - Path to the database file (optional).
 * @property screenshotSavePath - Path to save screenshots (optional).
 */
export interface UpdateSettingsRequest {
llm?: (LLMSettingsModel | null)
databasePath?: Databasepath
screenshotSavePath?: Screenshotsavepath
}
/**
 * LLM configuration model.
 * 
 * @property provider - The LLM provider (e.g., 'openai', 'qwen').
 * @property apiKey - The API key for the LLM provider.
 * @property model - The model name to use.
 * @property baseUrl - The base URL for the LLM API.
 */
export interface LLMSettingsModel {
provider: Provider
apiKey: Apikey
model: Model
baseUrl: Baseurl
}
/**
 * Request parameters for creating a new agent task.
 * 
 * @property agent - The agent type to use.
 * @property planDescription - The task description/plan.
 */
export interface CreateTaskRequest {
agent: Agent
planDescription: Plandescription
}
/**
 * Request parameters for executing a task.
 * 
 * @property taskId - The task ID to execute.
 */
export interface ExecuteTaskRequest {
taskId: Taskid
}
/**
 * Request parameters for deleting a task.
 * 
 * @property taskId - The task ID to delete.
 */
export interface DeleteTaskRequest {
taskId: Taskid1
}
/**
 * Request parameters for getting tasks.
 * 
 * @property limit - Maximum number of tasks to return (1-100).
 * @property status - Optional status filter.
 */
export interface GetTasksRequest {
limit?: Limit4
status?: Status
}
/**
 * Request parameters for getting available agents.
 * 
 * No parameters needed.
 */
export interface GetAvailableAgentsRequest {

}
export interface RootModelDict {
[k: string]: unknown
}
/**
 * 获取图片请求模型
 */
export interface GetImagesRequest {
hashes: Hashes
}
/**
 * 清理图片请求模型
 */
export interface CleanupImagesRequest {
maxAgeHours?: Maxagehours
}
