/* eslint-disable */
/**
 * This file was automatically generated by pytauri-gen-ts.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source commands API,
 * and run pytauri-gen-ts to regenerate this file.
 */

import { pyInvoke } from "tauri-plugin-pytauri-api";
import type { InvokeOptions } from "@tauri-apps/api/core";

import type { Commands } from "./_apiTypes.d.ts";

/**
 * A simple command that returns a greeting message.
 *
 * @param body - The person to greet.
 */
export async function greeting(
    body: Commands["greeting"]["input"],
    options?: InvokeOptions
): Promise<Commands["greeting"]["output"]> {
    return await pyInvoke("greeting", body, options);
}

/**
 * Get perception module statistics.
 *
 * Returns statistics about the perception module including record counts and status.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getPerceptionStats(
    body: Commands["get_perception_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_perception_stats"]["output"]> {
    return await pyInvoke("get_perception_stats", body, options);
}

/**
 * Get perception records with optional filters.
 *
 * @param body - Request parameters including limit and filters.
 * @returns Records data with success flag and timestamp
 */
export async function getRecords(
    body: Commands["get_records"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_records"]["output"]> {
    return await pyInvoke("get_records", body, options);
}

/**
 * Start the perception module.
 *
 * Starts monitoring keyboard, mouse, and screenshots.
 *
 * @returns Success response with message and timestamp
 */
export async function startPerception(
    body: Commands["start_perception"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_perception"]["output"]> {
    return await pyInvoke("start_perception", body, options);
}

/**
 * Stop the perception module.
 *
 * Stops monitoring keyboard, mouse, and screenshots.
 *
 * @returns Success response with message and timestamp
 */
export async function stopPerception(
    body: Commands["stop_perception"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_perception"]["output"]> {
    return await pyInvoke("stop_perception", body, options);
}

/**
 * Clear all perception records.
 *
 * Removes all stored records and clears the buffer.
 *
 * @returns Success response with message and timestamp
 */
export async function clearRecords(
    body: Commands["clear_records"]["input"],
    options?: InvokeOptions
): Promise<Commands["clear_records"]["output"]> {
    return await pyInvoke("clear_records", body, options);
}

/**
 * Get buffered events.
 *
 * Returns events currently in the buffer waiting to be processed.
 *
 * @returns Buffered events data with success flag and timestamp
 */
export async function getBufferedEvents(
    body: Commands["get_buffered_events"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_buffered_events"]["output"]> {
    return await pyInvoke("get_buffered_events", body, options);
}

/**
 * Get processing module statistics.
 *
 * Returns statistics about event and activity processing.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getProcessingStats(
    body: Commands["get_processing_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_processing_stats"]["output"]> {
    return await pyInvoke("get_processing_stats", body, options);
}

/**
 * Get processed events with optional filters.
 *
 * @param body - Request parameters including limit and filters.
 * @returns Events data with success flag and timestamp
 */
export async function getEvents(
    body: Commands["get_events"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_events"]["output"]> {
    return await pyInvoke("get_events", body, options);
}

/**
 * Get processed activities.
 *
 * @param body - Request parameters including limit.
 * @returns Activities data with success flag and timestamp
 */
export async function getActivities(
    body: Commands["get_activities"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activities"]["output"]> {
    return await pyInvoke("get_activities", body, options);
}

/**
 * Get event details by ID.
 *
 * @param body - Request parameters including event ID.
 * @returns Event details with success flag and timestamp
 */
export async function getEventById(
    body: Commands["get_event_by_id"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_event_by_id"]["output"]> {
    return await pyInvoke("get_event_by_id", body, options);
}

/**
 * Get activity details by ID.
 *
 * @param body - Request parameters including activity ID.
 * @returns Activity details with success flag and timestamp
 */
export async function getActivityById(
    body: Commands["get_activity_by_id"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activity_by_id"]["output"]> {
    return await pyInvoke("get_activity_by_id", body, options);
}

/**
 * Start the processing pipeline.
 *
 * Begins processing raw records into events and activities.
 *
 * @returns Success response with message and timestamp
 */
export async function startProcessing(
    body: Commands["start_processing"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_processing"]["output"]> {
    return await pyInvoke("start_processing", body, options);
}

/**
 * Stop the processing pipeline.
 *
 * Stops processing raw records.
 *
 * @returns Success response with message and timestamp
 */
export async function stopProcessing(
    body: Commands["stop_processing"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_processing"]["output"]> {
    return await pyInvoke("stop_processing", body, options);
}

/**
 * Force finalize the current activity.
 *
 * Forces the completion of the current activity being processed.
 *
 * @returns Success response with message and timestamp
 */
export async function finalizeCurrentActivity(
    body: Commands["finalize_current_activity"]["input"],
    options?: InvokeOptions
): Promise<Commands["finalize_current_activity"]["output"]> {
    return await pyInvoke("finalize_current_activity", body, options);
}

/**
 * Clean up old data.
 *
 * @param body - Request parameters including number of days to keep.
 * @returns Cleanup result with success flag and timestamp
 */
export async function cleanupOldData(
    body: Commands["cleanup_old_data"]["input"],
    options?: InvokeOptions
): Promise<Commands["cleanup_old_data"]["output"]> {
    return await pyInvoke("cleanup_old_data", body, options);
}

/**
 * Get persistence statistics.
 *
 * Returns statistics about data persistence including database size and record counts.
 *
 * @returns Statistics data with success flag and timestamp
 */
export async function getPersistenceStats(
    body: Commands["get_persistence_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_persistence_stats"]["output"]> {
    return await pyInvoke("get_persistence_stats", body, options);
}

/**
 * Get incremental activity updates based on version negotiation.
 *
 * This handler implements version-based incremental updates. The client provides
 * its current version number, and the server returns only activities created or
 * updated after that version.
 *
 * @param body - Request parameters including client version and limit.
 * @returns New activities data with success flag, max version, and timestamp
 */
export async function getActivitiesIncremental(
    body: Commands["get_activities_incremental"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activities_incremental"]["output"]> {
    return await pyInvoke("get_activities_incremental", body, options);
}

/**
 * Get activity count for each date (total count, not paginated).
 *
 * Returns the total number of activities for each date in the database.
 *
 * @param body - Request parameters (empty).
 * @returns Activity count statistics by date
 */
export async function getActivityCountByDate(
    body: Commands["get_activity_count_by_date"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_activity_count_by_date"]["output"]> {
    return await pyInvoke("get_activity_count_by_date", body, options);
}

/**
 * 启动整个后端系统（perception + processing）
 *
 * @returns Success response with message and timestamp
 */
export async function startSystem(
    body: Commands["start_system"]["input"],
    options?: InvokeOptions
): Promise<Commands["start_system"]["output"]> {
    return await pyInvoke("start_system", body, options);
}

/**
 * 停止整个后端系统
 *
 * @returns Success response with message and timestamp
 */
export async function stopSystem(
    body: Commands["stop_system"]["input"],
    options?: InvokeOptions
): Promise<Commands["stop_system"]["output"]> {
    return await pyInvoke("stop_system", body, options);
}

/**
 * 获取系统整体状态
 *
 * @returns System statistics with perception and processing info
 */
export async function getSystemStats(
    body: Commands["get_system_stats"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_system_stats"]["output"]> {
    return await pyInvoke("get_system_stats", body, options);
}

/**
 * 获取后端正在使用的数据库绝对路径
 */
export async function getDatabasePath(
    body: Commands["get_database_path"]["input"],
    options?: InvokeOptions
): Promise<Commands["get_database_path"]["output"]> {
    return await pyInvoke("get_database_path", body, options);
}
